apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: mywebsite
    tier: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: gouravakscluster
      labels:
        app: gouravakscluster
    spec:
      containers:
        - name: gouravakscluster
          image: acrgourav.azurecr.io/gouravpatelspringboot
          ports:
           - containerPort: 8080
  selector:
    matchLabels:
      app: gouravakscluster
