apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myakscluster
    spec:
      containers:
        - name: "myakscluster"
          image: "acrgourav.azurecr.io/gouravpatelspringboot"
          ports:
          - containerPort: 8080
    selector:
     matchLabels:
      app: myakscluster
