apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "gauravakscluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "myakscluster"
    spec:
      containers:
        - name: "gauravakscluster"
          image: "gauravregistry.azurecr.io/gauravakscluster"
          ports:
          - containerPort: 8080
