apiVersion : apps/v1
kind: Deployment
metadata:
  name: "gouravakscluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gouravakscluster
    spec:
      containers:
        - name: "gouravakscluster"
          image: "acrgourav.azurecr.io/gouravpatelspringboot"
          ports:
          - containerPort: 8080
    selector:
     matchLabels:
      app: gouravakscluster
