apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "gaurav-akscluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "gaurav-akscluster"
    spec:
      containers:
        - name: "gaurav-akscluster"
          image: "gauravregistry.azurecr.io/gaurav-akscluster"
          ports:
          - containerPort: 8080
