---
apiVersion: v1
kind: Service
metadata:
    name: "gouravakscluster"
    labels:
        app: gouravakscluster
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: gouravakscluster
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gouravakscluster
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: gouravakscluster.a694aaf205694363b0c9.westeurope.aksapp.io
    http:
      paths:
       - path: /hello
         backend:
          serviceName: gouravakscluster
          servicePort: 80
